name: Update Starter Projects
on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  update-starter-projects:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Setup Environment"
        uses: ./.github/actions/setup-uv

      - name: "Install dependencies"
        run: |
          uv sync --frozen
          uv pip install -e .

      - name: Debug environment
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Python path:"
          python -c "import sys; print('\n'.join(sys.path))"
          echo "Installed packages:"
          uv pip list
          echo "Python version:"
          python --version

      - name: Run starter projects update
        run: uv run python scripts/ci/update_starter_projects.py

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c

      - name: Minimize uv cache
        run: uv cache prune --ci

